apiVersion: v1
kind: Service
metadata:
  name: model-service
spec:
  selector:
    app: model
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  sessionAffinity: None  # Add this line
